import SwiftUI
import PDFKit

struct PDFKitView: UIViewRepresentable {
    let document: PDFDocument?
    
    func makeUIView(context: Context) -> PDFView {
        let pdfView = PDFView()
        pdfView.document = document
        pdfView.autoScales = true
        pdfView.displayMode = .singlePageContinuous
        pdfView.displayDirection = .vertical
        return pdfView
    }
    
    func updateUIView(_ uiView: PDFView, context: Context) {
        uiView.document = document
    }
}

class PDFGenerator {
    static func generateDummyReport() -> PDFDocument? {
        let format = UIGraphicsPDFRendererFormat()
        let metaData = [
            kCGPDFContextTitle: "BSAI Analytics Report",
            kCGPDFContextAuthor: "BSAI System"
        ]
        format.documentInfo = metaData as [String: Any]
        
        let pageWidth = 8.5 * 72.0
        let pageHeight = 11.0 * 72.0
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect, format: format)
        
        let data = renderer.pdfData { context in
            context.beginPage()
            
            // Draw Header Background
            context.cgContext.setFillColor(UIColor(red: 0.0, green: 0.78, blue: 0.32, alpha: 1.0).cgColor)
            context.cgContext.fill(CGRect(x: 0, y: 0, width: pageWidth, height: 120))
            
            // Title
            let title = "BSAI Comprehensive Report"
            let attributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 28, weight: .bold),
                .foregroundColor: UIColor.white
            ]
            let attributedTitle = NSAttributedString(string: title, attributes: attributes)
            attributedTitle.draw(at: CGPoint(x: 40, y: 45))
            
            // Content
            let formatter = DateFormatter()
            formatter.dateStyle = .long
            let dateString = formatter.string(from: Date())
            
            let content = """
            Generated on \(dateString)
            
            This is an autogenerated mock PDF report utilizing iOS PDFKit.
            In a production environment, this PDF will contain rich analytic charts, automated AI breed detection summaries, and validated farmer registration data points.
            
            Key Highlights:
            • Over 2,800 registered cattle and buffalo entries.
            • Automated AI classification with 95%+ precision.
            • Geolocation tracing and tagging securely finalized.
            
            (End of demonstration PDF)
            """
            
            let contentAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 14),
                .foregroundColor: UIColor.darkText
            ]
            let attributedContent = NSAttributedString(string: content, attributes: contentAttributes)
            
            let textRect = CGRect(x: 40, y: 150, width: pageWidth - 80, height: pageHeight - 180)
            attributedContent.draw(in: textRect)
        }
        
        return PDFDocument(data: data)
    }
}

struct PDFReportViewer: View {
    @Environment(\.presentationMode) var presentationMode
    let title: String
    
    @State private var pdfDocument: PDFDocument?
    @State private var pdfURL: URL?
    
    var body: some View {
        NavigationView {
            ZStack {
                Color(UIColor.systemGroupedBackground).ignoresSafeArea()
                if let doc = pdfDocument {
                    PDFKitView(document: doc)
                        .shadow(color: .black.opacity(0.1), radius: 10)
                        .padding()
                } else {
                    VStack(spacing: 20) {
                        ProgressView()
                            .scaleEffect(1.5)
                        Text("Generating PDF...")
                            .foregroundColor(.secondary)
                    }
                }
            }
            .navigationTitle(title)
            .navigationBarTitleDisplayMode(.inline)
            .navigationBarItems(
                leading: Button("Done") {
                    presentationMode.wrappedValue.dismiss()
                },
                trailing: Group {
                    if let url = pdfURL {
                        ShareLink(item: url, subject: Text(title), message: Text("Here is the BSAI PDF report."))
                    } else {
                        EmptyView()
                    }
                }
            )
            .onAppear {
                generatePDF()
            }
        }
    }
    
    private func generatePDF() {
        DispatchQueue.global(qos: .userInitiated).async {
            if let doc = PDFGenerator.generateDummyReport() {
                let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(title.replacingOccurrences(of: " ", with: "_")).pdf")
                doc.write(to: tempURL)
                
                DispatchQueue.main.async {
                    self.pdfDocument = doc
                    self.pdfURL = tempURL
                }
            }
        }
    }
}
